name: Build LKM Module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up swap
        shell: bash
        run: |
          sudo swapoff -a
          sudo fallocate -l 10G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon -s
          free -h

      - name: Set up ccache
        uses: actions/cache@v4
        with:
          path: |
            ~/.ccache
          key: ccache-${{ github.sha }}
          restore-keys: |
            ccache-${{ github.sha }}

      - name: Checkout kernel source code
        uses: actions/checkout@v4
        with:
          repository: yoro1836/Kren_kernel
          ref: S908EXXUBEXK5
          path: kernel_source

      - name: Checkout module source code
        uses: actions/checkout@v4
        with:
          repository: lwfinger/rtw88
          path: module_source

      - name: Set up build environment
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev bison flex openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev
          sudo apt-get install -y ccache
          echo " " >> ~/.bashrc
          echo "export USE_CCACHE=1" >> ~/.bashrc
          source ~/.bashrc
          ccache -M 5G
          ccache -s
          wget https://github.com/ZyCromerZ/Clang/releases/download/12.0.1-20230207-release/Clang-12.0.1-20230207.tar.gz -O toolchain.tar.gz
          mkdir toolchain
          tar -xzf toolchain.tar.gz -C toolchain
          export PATH=$PATH:$(pwd)/toolchain/bin
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gas/linux-x86 -b main $WORKDIR/binutils
          export PATH="$WORKDIR/binutils:$PATH"

      - name: Prepare kernel headers and build directory
        shell: bash
        working-directory: kernel_source
        run: |
          cp arch/arm64/configs/kren_defconfig .config
           make \
            ARCH=arm64 \
            LLVM=1 \
            LLVM_IAS=1 \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
            LD=ld.lld \
            AR=ar \
            kren_defconfig
          make headers_install
          make modules_prepare

      - name: Compile LKM module
        shell: bash
        working-directory: module_source
        run: |
          make -j$(nproc) -C /lib/modules/5.10.234-Kren/build M=$(pwd) modules

      - name: Upload LKM module artifact
        uses: actions/upload-artifact@v4
        with:
          name: rtw88.ko
          path: module_source/rtw88.ko
